export const INGREDIENTS_LOAD = 'INGREDIENTS_LOAD';
export const INGREDIENTS_LOAD_CONSTR = 'INGREDIENTS_LOAD_CONSTR';
export const INGREDIENTS_VIEW_DETAILS = 'INGREDIENTS_VIEW_DETAILS';
export const INGREDIENTS_DELETE_DETAILS = 'INGREDIENTS_DELETE_DETAILS';
export const ORDER_NUMBER = 'ORDER_NUMBER';
