export const INGREDIENTS_LOAD : 'INGREDIENTS_LOAD' = 'INGREDIENTS_LOAD';
export const INGREDIENTS_LOAD_CONSTR : 'INGREDIENTS_LOAD_CONSTR' = 'INGREDIENTS_LOAD_CONSTR';
export const INGREDIENTS_VIEW_DETAILS : 'INGREDIENTS_VIEW_DETAILS' = 'INGREDIENTS_VIEW_DETAILS';
export const INGREDIENTS_DELETE_DETAILS : 'INGREDIENTS_DELETE_DETAILS' = 'INGREDIENTS_DELETE_DETAILS';

export const ORDER_LOAD : 'ORDER_LOAD' = 'ORDER_LOAD';
export const GET_ORDER = 'GET_ORDER';
export const GET_ORDER_FAILED = 'GET_ORDER_FAILED';
export const GET_ORDER_SUCCESS = 'GET_ORDER_SUCCESS';
export const CLEAR_ORDER = 'CLEAR_ORDER'

export const INGREDIENTS_CHOOSE : 'INGREDIENTS_CHOOSE' = 'INGREDIENTS_CHOOSE'; // выбор ингредиентов
export const INGREDIENT_DELETE : 'INGREDIENT_DELETE' = 'INGREDIENT_DELETE';

export const COUNTER_UP : 'COUNTER_UP' = 'COUNTER_UP';
export const COUNTER_DOWN : 'COUNTER_DOWN' = 'COUNTER_DOWN';
export const MOVE_INGREDIENT : 'MOVE_INGREDIENT' = 'MOVE_INGREDIENT';
export const RESET_CONSTRUCTOR : 'RESET_CONSTRUCTOR' = 'RESET_CONSTRUCTOR';

